# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_facebookaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
