services:
  web:
    build: ./web
    container_name: lucos_contacts_web
    ports:
      - "8013:80"
    image: lucas42/lucos_contacts_web
    volumes:
      - "staticfiles:/usr/share/nginx/html/resources"
    restart: always
    depends_on:
      - app
  app:
    build: ./app
    container_name: lucos_contacts_app
    image: lucas42/lucos_contacts_app
    environment:
      - SECRET_KEY
      - PRODUCTION
      - CLIENT_KEYS
    volumes:
      - "staticfiles:/usr/src/app/static"
    restart: always
    depends_on:
      - db
  db:
    container_name: lucos_contacts_db
    image: postgres:16-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
  test:
    build: ./app
    container_name: lucos_contacts_test
    image: lucas42/lucos_contacts_app
    environment:
      - SECRET_KEY=test
      - CLIENT_KEYS=
    depends_on:
      - db
    command: ./manage.py test agents.tests comms.tests lucosauth.tests
volumes:
  staticfiles:
  db_data: