version: '3'
services:
  web:
    build: ./web
    container_name: contacts_web
    ports:
      - "8013:80"
    image: lucas42/lucos_contacts_web
    volumes:
      - "staticfiles:/usr/share/nginx/html/resources"
    restart: always
    depends_on:
      - app
  app:
    build: ./app
    container_name: contacts_app
    image: lucas42/lucos_contacts_app
    environment:
      - SECRET_KEY
      - PRODUCTION
    volumes:
      - "staticfiles:/usr/src/app/static"
    restart: always
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
volumes:
  staticfiles:
  db_data: