# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-09 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucosauth', '0002_auto_20170716_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('system', models.CharField(max_length=127)),
                ('apikey', models.CharField(max_length=127)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
