# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-10 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lucosauth', '0003_apiuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='apikey',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='system',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
