# Generated by Django 5.2.5 on 2025-08-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lucosauth', '0004_auto_20190610_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiUser',
        ),
    ]
