# Generated by Django 3.1.4 on 2020-12-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0021_auto_20201005_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChristmasList',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('gave_card_to', models.ManyToManyField(related_name='gave_card_to', to='agents.Agent')),
                ('received_card_from', models.ManyToManyField(related_name='received_card_from', to='agents.Agent')),
            ],
        ),
    ]
