# Generated by Django 3.2.14 on 2022-07-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0030_alter_relationship_relationshiptype'),
        ('comms', '0003_alter_christmaslist_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='christmaslist',
            name='gave_card_to',
            field=models.ManyToManyField(blank=True, related_name='gave_card_to', to='agents.Agent'),
        ),
        migrations.AlterField(
            model_name='christmaslist',
            name='received_card_from',
            field=models.ManyToManyField(blank=True, related_name='received_card_from', to='agents.Agent'),
        ),
    ]
