# Generated by Django 5.1.7 on 2025-03-19 23:52

import django.db.models.deletion
from django.db import migrations, models

def copy_christmas_list_to_occasionlist(apps, schema_editor):
    ChristmasList = apps.get_model('comms', 'ChristmasList')
    OccasionList = apps.get_model('comms', 'OccasionList')

    # Loop through all existing ChristmasLists
    for christmas_list in ChristmasList.objects.all():
        # Create a corresponding OccasionList for each ChristmasList
        occasion_list = OccasionList.objects.create(
            type='Christmas',  # Set the type as Christmas
            year=christmas_list.year
        )

        # Copy over the many-to-many relationships (gave_card_to, received_card_from)
        for card in christmas_list.gave_card_to.all():
            occasion_list.gave_card_to.add(card)
        for card in christmas_list.received_card_from.all():
            occasion_list.received_card_from.add(card)
        occasion_list.save()


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0039_auto_20230101_2202'),
        ('comms', '0004_auto_20220709_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_given', models.BooleanField(help_text="Whether I gave or received the present", choices=((True, 'Given'), (False, 'Received')), default=True)),
                ('description', models.CharField(help_text="E.g. 'Handmade Scarf', 'Book'", max_length=255)),
                ('agents', models.ManyToManyField(blank=True, related_name='presents', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='OccasionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Christmas', 'Christmas'), ('Birthday', 'Birthday'), ('Other', 'Other')], default='Other', max_length=20)),
                ('year', models.IntegerField(help_text="Calendar year, as per the Gregorian Calendar (Common Era assumed)")),
                ('gave_card_to', models.ManyToManyField(blank=True, related_name='gave_card_to', to='agents.agent')),
                ('received_card_from', models.ManyToManyField(blank=True, related_name='received_card_from', to='agents.agent')),
            ],
            options={
                'unique_together': {('type', 'year')},
            },
        ),
        migrations.CreateModel(
            name='BirthdayPresent',
            fields=[
                ('present_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='comms.present')),
                ('year', models.IntegerField()),
            ],
            bases=('comms.present',),
        ),
        migrations.AddField(
            model_name='present',
            name='occasion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presents', to='comms.occasionlist', null=True, blank=True),
        ),
        migrations.RunPython(copy_christmas_list_to_occasionlist),
        migrations.DeleteModel(
            name='ChristmasList',
        ),
    ]
