# Generated by Django 5.1.7 on 2025-03-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0005_present_occasionlist_birthdaypresent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='birthdaypresent',
            options={'verbose_name': 'birthday present', 'verbose_name_plural': 'birthday presents'},
        ),
        migrations.AlterModelOptions(
            name='occasionlist',
            options={'verbose_name': 'occasion list', 'verbose_name_plural': 'occasion lists'},
        ),
        migrations.AlterModelOptions(
            name='present',
            options={'verbose_name': 'present', 'verbose_name_plural': 'presents'},
        ),
        migrations.AlterField(
            model_name='birthdaypresent',
            name='year',
            field=models.IntegerField(help_text='The calendar year of the birthday the present was for (which is usually, but not necessarily, the year the present was given)'),
        ),
    ]
