# Generated by Django 5.1.7 on 2025-03-22 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0039_auto_20230101_2202'),
        ('comms', '0006_alter_birthdaypresent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaypresent',
            name='year',
            field=models.IntegerField(help_text='The calendar year of the birthday the present was for (which is usually, but not necessarily, the year the present was given)', verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='occasionlist',
            name='gave_card_to',
            field=models.ManyToManyField(blank=True, related_name='gave_card_to', to='agents.agent', verbose_name='gave card to'),
        ),
        migrations.AlterField(
            model_name='occasionlist',
            name='received_card_from',
            field=models.ManyToManyField(blank=True, related_name='received_card_from', to='agents.agent', verbose_name='received card from'),
        ),
        migrations.AlterField(
            model_name='occasionlist',
            name='year',
            field=models.IntegerField(help_text='Calendar year, as per the Gregorian Calendar (Common Era assumed)', verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='present',
            name='agents',
            field=models.ManyToManyField(blank=True, related_name='presents', to='agents.agent', verbose_name='agent'),
        ),
        migrations.AlterField(
            model_name='present',
            name='description',
            field=models.CharField(help_text="E.g. 'Handmade Scarf', 'Book'", max_length=255, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='present',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presents', to='comms.occasionlist', verbose_name='occasion'),
        ),
        migrations.AlterField(
            model_name='present',
            name='was_given',
            field=models.BooleanField(choices=[(True, 'Given'), (False, 'Received')], default=True, help_text='Whether I gave or received the present', verbose_name='was given'),
        ),
    ]
