# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-22 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_auto_20170730_0345'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='gift_ideas',
            field=models.TextField(blank=True),
        ),
    ]
