# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-16 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_auto_20190616_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookaccount',
            name='userid',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='googleaccount',
            name='userid',
            field=models.CharField(max_length=255),
        ),
    ]
