# Generated by Django 3.0.3 on 2020-08-25 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_auto_20190619_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facebookaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='googleaccount',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='googlecontact',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postaladdress',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='type',
            field=models.ForeignKey(help_text='Subject is a $type of object', on_delete=django.db.models.deletion.CASCADE, to='agents.RelationshipType'),
        ),
    ]
