# Generated by Django 3.1 on 2020-08-31 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_relationship_relationshiptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationshipType',
            field=models.CharField(choices=[('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('grandparent', 'Grandparent'), ('aunt/uncle', 'AuntOrUncle'), ('nibling', 'Nibling'), ('ancestor', 'Ancestor'), ('great aunt/uncle', 'GreatAuntOrGreatUncle'), ('half-sibling', 'HalfSibling')], max_length=127),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Subject is a $type of object', on_delete=django.db.models.deletion.CASCADE, to='agents.relationshiptype'),
        ),
    ]
