# Generated by Django 3.1 on 2020-09-05 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_auto_20200831_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='type',
            field=models.ForeignKey(blank=True, help_text='Subject is a $type of object', null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.relationshiptype'),
        ),
    ]
