# Generated by Django 3.1 on 2020-09-07 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_auto_20200905_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationshiptypeconnection',
            name='inferred_relation_type',
        ),
        migrations.RemoveField(
            model_name='relationshiptypeconnection',
            name='relation_type_a',
        ),
        migrations.RemoveField(
            model_name='relationshiptypeconnection',
            name='relation_type_b',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='type',
        ),
        migrations.DeleteModel(
            name='RelationshipType',
        ),
        migrations.DeleteModel(
            name='RelationshipTypeConnection',
        ),
    ]
