# Generated by Django 3.1 on 2020-09-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_auto_20200913_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='relationshipType',
            field=models.CharField(choices=[('child', 'Páiste'), ('parent', 'Tuismitheoir'), ('sibling', 'Siblín'), ('half-sibling', 'Leath-Siblín'), ('grandchild', 'Garpháiste'), ('grandparent', 'Seantuismitheoir'), ('aunt/uncle', 'Aunt/Uncle'), ('nibling', 'Nibling'), ('great aunt/uncle', 'Great Aunt/Uncle'), ('great nibling', 'Great Nibling'), ('first cousin', 'Col Ceathrair')], max_length=127),
        ),
    ]
