# Generated by Django 3.2.6 on 2021-09-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0025_agentname_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentname',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
