# Generated by Django 3.2.6 on 2021-10-03 01:00

from django.db import migrations, models

## Iterates through the names in each language field and creates new AgentNames for them
def copy_names(apps, schema_editor):
    Agent = apps.get_model('agents', 'Agent')
    AgentName = apps.get_model('agents', 'AgentName')
    for agent in Agent.objects.all():
        langs = ['ga', 'en', 'gd', 'cy']
        firstDone = False
        for ii in langs:    
            val = getattr(agent, 'name_'+ii, None)
            if val:
                agentName = AgentName.objects.create(agent=agent,name=val)
                if not firstDone:
                    agentName.is_primary = True
                    agent._name = val
                    agent.save()
                    firstDone = True
                agentName.save()

## Stick the names back in the old name fields without preserving exact lang mappings
def revert_names(apps, schema_editor):
    Agent = apps.get_model('agents', 'Agent')
    AgentName = apps.get_model('agents', 'AgentName')
    for agent in Agent.objects.all():
        langs = ['en', 'ga', 'gd', 'cy']
        for name in AgentName.objects.filter(agent=agent):
            setattr(agent, "name_"+langs.pop(), name.name)
            agent.save()

class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0026_alter_agentname_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(copy_names, revert_names),
        migrations.RemoveField(
            model_name='agent',
            name='name_cy',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='name_ga',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='name_gd',
        ),
    ]
