# Generated by Django 3.2.6 on 2021-10-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0027_migrate_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='_name',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
