# Generated by Django 3.2.15 on 2022-10-17 21:47

from django.db import migrations
import phonenumber_field.modelfields

def standardise_numbers(apps, schema_editor):
    PhoneNumber = apps.get_model('agents', 'PhoneNumber')
    for phone in PhoneNumber.objects.all():
        phone.save(force_update=True)


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0030_alter_relationship_relationshiptype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.RunPython(standardise_numbers),
    ]
