# Generated by Django 3.2.15 on 2022-10-17 21:47

from django.db import migrations
import phonenumber_field.modelfields

def convert_contact_ids(apps, schema_editor):
    GoogleContact = apps.get_model('agents', 'GoogleContact')
    for googlecontact in GoogleContact.objects.all():
        oldContactAPIID = googlecontact.contactid

        # Algorithm for conversion found here: https://stackoverflow.com/questions/46349746/is-there-any-way-that-i-can-retrieve-account-id-from-google-contact-api-v3-to-ma/46355535#46355535
        try:
            newPeopleAPIID = "c"+str(int(oldContactAPIID, base=16))
            print("Convert "+oldContactAPIID+" to "+newPeopleAPIID)
        except:
            print("Can't convert \""+oldContactAPIID+"\" to google people API ID")
            continue

        googlecontact.contactid = newPeopleAPIID
        googlecontact.save()


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0031_alter_phonenumber_number'),
    ]

    operations = [
        migrations.RunPython(convert_contact_ids),
    ]
