# Generated by Django 3.2.16 on 2022-11-09 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0032_migrate_google_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GooglePhotosProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('person_id', models.PositiveBigIntegerField()),
                ('cluster_media_key', models.CharField(blank=True, max_length=255)),
                ('search_path', models.CharField(blank=True, max_length=255)),
                ('profile_pic_url', models.CharField(blank=True, max_length=1023)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
