# Generated by Django 3.2.16 on 2022-12-29 14:35

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0034_remove_googlephotosprofile_profile_pic_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': [django.db.models.functions.text.Lower('_name')]},
        ),
    ]
