# Generated by Django 3.2.16 on 2022-12-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0035_alter_agent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailaddress',
            options={'verbose_name': 'email address', 'verbose_name_plural': 'email addresses'},
        ),
        migrations.AlterModelOptions(
            name='facebookaccount',
            options={'verbose_name': 'facebook account', 'verbose_name_plural': 'facebook accounts'},
        ),
        migrations.AlterModelOptions(
            name='googleaccount',
            options={'verbose_name': 'google account', 'verbose_name_plural': 'google accounts'},
        ),
        migrations.AlterModelOptions(
            name='googlecontact',
            options={'verbose_name': 'google contact', 'verbose_name_plural': 'google contacts'},
        ),
        migrations.AlterModelOptions(
            name='googlephotosprofile',
            options={'verbose_name': 'google photos profile', 'verbose_name_plural': 'google photos profiles'},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'phone number', 'verbose_name_plural': 'phone numbers'},
        ),
        migrations.AlterModelOptions(
            name='postaladdress',
            options={'verbose_name': 'postal address', 'verbose_name_plural': 'postal addresses'},
        ),
    ]
