# Generated by Django 5.2.5 on 2025-08-10 15:20

import django.db.models.deletion
from django.db import migrations, models

# Migration assumes all romanticRelationships have two members, and uses the new `romanticPartner` field to connect them
def copy_members(apps, schema_editor):
    RomanticRelationship = apps.get_model("agents", "RomanticRelationship")
    for roRel in RomanticRelationship.objects.all():
        members = roRel.members.all()
        roRel.personA = members[0]
        roRel.personB = members[1]
        roRel.save()

class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0039_auto_20230101_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='romanticrelationship',
            name='personA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personA', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='romanticrelationship',
            name='personB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personB', to='agents.agent'),
        ),
        migrations.RunPython(copy_members),
    ]
