# Generated by Django 5.2.5 on 2025-08-10 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0040_romanticrelationship_persona_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='romanticrelationship',
            name='members',
        ),
        migrations.AlterField(
            model_name='romanticrelationship',
            name='personA',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personA', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='romanticrelationship',
            name='personB',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personB', to='agents.agent'),
        ),
    ]
