# Generated by Django 5.2.5 on 2025-08-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0041_remove_romanticrelationship_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='on_gift_list',
        ),
    ]
