# Generated by Django 5.2.6 on 2025-09-08 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0042_remove_agent_on_gift_list'),
        ('comms', '0007_alter_birthdaypresent_year_and_more'),
        ('lucosauth', '0005_delete_apiuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExternalAgent',
            new_name='ExternalPerson',
        ),
        migrations.RenameModel(
            old_name='Agent',
            new_name='Person',
        ),
        migrations.RenameModel(
            old_name='AgentName',
            new_name='PersonName',
        ),
    ]
