# Generated by Django 5.2.6 on 2025-09-08 15:06

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0043_rename_externalagent_externalperson_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': [django.db.models.functions.text.Lower('_name')], 'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
    ]
