# Generated by Django 6.0.2 on 2026-02-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0044_alter_person_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('subject', 'object', 'relationshipType')},
        ),
    ]
