# Generated by Django 6.0.5 on 2026-05-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0045_alter_relationship_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='eolas_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
