# Generated by Django 6.0.7 on 2026-07-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0046_person_eolas_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='emailaddress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('agent',), name='unique_primary_email_per_agent'),
        ),
    ]
